### ISSUE TITLE
Not yet release to Crates.io

### ISSUE THREAD

**Issue by tisonkun** [apache/incubator-horaedb-proto#130]
https://crates.io/crates/horaedbproto doesn't contain the 2.0.0 release.

cc @jiacai2050 @tanruixiang

**Comment by tanruixiang** [comment]
@jiacai2050 This crates still contains information from ceresdb and I don't have access to make changes, can you help with the process of posting to crates?

**Comment by jiacai2050** [comment]
https://crates.io/crates/horaedbproto/2.0.0 Released
